apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-deployment
  namespace:  mytg
  labels:
    app: mydb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
         - containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            secretKeyRef:
                     name: mariadbtest
                     key: password
