apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp6
  namespace: tg
  labels:
    app: mydb
spec:
  replicas: 5
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - name: mariadb
        image: mysql:5.7.42
        ports:
         - containerPort: 3306
        env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            configMapKeyRef:
                     name: mysqlcm
                     key: mydbpass
