apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  namespace: tg
  labels:
    env: prod
spec:
  nodeName: wn1.tgindia.com
  volumes:
    - name: myvol1
      hostPath:
        path: "/opt/webdata"
        type: Directory
  containers:
    - name: cont1
      image: nginx
      volumeMounts:
      - name: myvol1
        mountPath: "/usr/share/nginx/html"
        readOnly: true

          #          -v  "/opt/webdata:/usr/share/nginx/html"